
def tabela_votacao_candidato(ano=None):
    return [
        'DATA_GERACAO',
        'HORA_GERACAO',
        'ANO_ELEICAO',
        'NUM_TURNO',
        'DESCRICAO_ELEICAO',
        'SIGLA_UF',
        'SIGLA_UE',
        'CODIGO_CARGO',
        'NUMERO_CAND',
        'SQ_CANDIDATO',
        'NOME_CANDIDATO',
        'NOME_URNA_CANDIDATO',
        'DESCRICAO_CARGO',
        'COD_SIT_CAND_SUPERIOR',
        'DESC_SIT_CAND_SUPERIOR',
        'CODIGO_SIT_CANDIDATO',
        'DESC_SIT_CANDIDATO',
        'CODIGO_SIT_CAND_TOT',
        'DESC_SIT_CAND_TOT',
        'NUMERO_PARTIDO',
        'SIGLA_PARTIDO',
        'NOME_PARTIDO',
        'SEQUENCIAL_LEGENDA',
        'NOME_COLIGACAO',
        'COMPOSICAO_LEGENDA',
        'TOTAL_VOTOS'
    ]

def tabela_consulta_cand(ano):
    if ano <= 2010:
        return [
            'DATA_GERACAO',
            'HORA_GERACAO',
            'ANO_ELEICAO',
            'NUM_TURNO',
            'DESCRICAO_ELEICAO',
            'SIGLA_UF',
            'SIGLA_UE',
            'DESCRICAO_UE',
            'CODIGO_CARGO',
            'DESCRICAO_CARGO',
            'NOME_CANDIDATO',
            'SEQUENCIAL_CANDIDATO',
            'NUMERO_CANDIDATO',
            'CPF_CANDIDATO',
            'NOME_URNA_CANDIDATO',
            'COD_SITUACAO_CANDIDATURA',
            'DES_SITUACAO_CANDIDATURA',
            'NUMERO_PARTIDO',
            'SIGLA_PARTIDO',
            'NOME_PARTIDO',
            'CODIGO_LEGENDA',
            'SIGLA_LEGENDA',
            'COMPOSICAO_LEGENDA',
            'NOME_LEGENDA',
            'CODIGO_OCUPACAO',
            'DESCRICAO_OCUPACAO',
            'DATA_NASCIMENTO',
            'NUM_TITULO_ELEITORAL_CANDIDATO',
            'IDADE_DATA_ELEICAO',
            'CODIGO_SEXO',
            'DESCRICAO_SEXO',
            'COD_GRAU_INSTRUCAO',
            'DESCRICAO_GRAU_INSTRUCAO',
            'CODIGO_ESTADO_CIVIL',
            'DESCRICAO_ESTADO_CIVIL',
            'CODIGO_NACIONALIDADE',
            'DESCRICAO_NACIONALIDADE',
            'SIGLA_UF_NASCIMENTO',
            'CODIGO_MUNICIPIO_NASCIMENTO',
            'NOME_MUNICIPIO_NASCIMENTO',
            'DESPESA_MAX_CAMPANHA',
            'COD_SIT_TOT_TURNO',
            # 'DESC_SIT_TOT_TURNO'
        ]

    elif ano == 2012:
        return [
            'DATA_GERACAO',
            'HORA_GERACAO',
            'ANO_ELEICAO',
            'NUM_TURNO',
            'DESCRICAO_ELEICAO',
            'SIGLA_UF',
            'SIGLA_UE',
            'DESCRICAO_UE',
            'CODIGO_CARGO',
            'DESCRICAO_CARGO',
            'NOME_CANDIDATO',
            'SEQUENCIAL_CANDIDATO',
            'NUMERO_CANDIDATO',
            'CPF_CANDIDATO',
            'NOME_URNA_CANDIDATO',
            'COD_SITUACAO_CANDIDATURA',
            'DES_SITUACAO_CANDIDATURA',
            'NUMERO_PARTIDO',
            'SIGLA_PARTIDO',
            'NOME_PARTIDO',
            'CODIGO_LEGENDA',
            'SIGLA_LEGENDA',
            'COMPOSICAO_LEGENDA',
            'NOME_LEGENDA',
            'CODIGO_OCUPACAO',
            'DESCRICAO_OCUPACAO',
            'DATA_NASCIMENTO',
            'NUM_TITULO_ELEITORAL_CANDIDATO',
            'IDADE_DATA_ELEICAO',
            'CODIGO_SEXO',
            'DESCRICAO_SEXO',
            'COD_GRAU_INSTRUCAO',
            'DESCRICAO_GRAU_INSTRUCAO',
            'CODIGO_ESTADO_CIVIL',
            'DESCRICAO_ESTADO_CIVIL',
            'CODIGO_NACIONALIDADE',
            'DESCRICAO_NACIONALIDADE',
            'SIGLA_UF_NASCIMENTO',
            'CODIGO_MUNICIPIO_NASCIMENTO',
            'NOME_MUNICIPIO_NASCIMENTO',
            'DESPESA_MAX_CAMPANHA',
            'COD_SIT_TOT_TURNO',
            'DESC_SIT_TOT_TURNO'
        ]

    elif ano >= 2014:
        return [
            'DATA_GERACAO',
            'HORA_GERACAO',
            'ANO_ELEICAO',
            'NUM_TURNO',
            'DESCRICAO_ELEICAO',
            'SIGLA_UF',
            'SIGLA_UE',
            'DESCRICAO_UE',
            'CODIGO_CARGO',
            'DESCRICAO_CARGO',
            'NOME_CANDIDATO',
            'SEQUENCIAL_CANDIDATO',
            'NUMERO_CANDIDATO',
            'CPF_CANDIDATO',
            'NOME_URNA_CANDIDATO',
            'COD_SITUACAO_CANDIDATURA',
            'DES_SITUACAO_CANDIDATURA',
            'NUMERO_PARTIDO',
            'SIGLA_PARTIDO',
            'NOME_PARTIDO',
            'CODIGO_LEGENDA',
            'SIGLA_LEGENDA',
            'COMPOSICAO_LEGENDA',
            'NOME_LEGENDA',
            'CODIGO_OCUPACAO',
            'DESCRICAO_OCUPACAO',
            'DATA_NASCIMENTO',
            'NUM_TITULO_ELEITORAL_CANDIDATO',
            'IDADE_DATA_ELEICAO',
            'CODIGO_SEXO',
            'DESCRICAO_SEXO',
            'COD_GRAU_INSTRUCAO',
            'DESCRICAO_GRAU_INSTRUCAO',
            'CODIGO_ESTADO_CIVIL',
            'DESCRICAO_ESTADO_CIVIL',
            'CODIGO_COR_RACA',
            'DESCRICAO_COR_RACA',
            'CODIGO_NACIONALIDADE',
            'DESCRICAO_NACIONALIDADE',
            'SIGLA_UF_NASCIMENTO',
            'CODIGO_MUNICIPIO_NASCIMENTO',
            'NOME_MUNICIPIO_NASCIMENTO',
            'DESPESA_MAX_CAMPANHA',
            'COD_SIT_TOT_TURNO',
            'DESC_SIT_TOT_TURNO'
        ]

def tabela_voto_secao(ano=None):
    return [
        'DATA_GERACAO',
        'HORA_GERACAO',
        'ANO_ELEICAO',
        'NUM_TURNO',
        'DESCRICAO_ELEICAO',
        'SIGLA_UF',
        'SIGLA_UE',
        'CODIGO_MUNICIPIO',
        'NOME_MUNICIPIO',
        'NUM_ZONA',
        'NUM_SECAO',
        'CODIGO_CARGO',
        'DESCRICAO_CARGO',
        'NUM_VOTAVEL',
        'QTDE_VOTOS'
    ]


def tabela_votacao_candidato_munzona(ano=None):
    if ano <= 2012:
        return [
            'DATA_GERACAO',
            'HORA_GERACAO',
            'ANO_ELEICAO',
            'NUM_TURNO',
            'DESCRICAO_ELEICAO',
            'SIGLA_UF',
            'SIGLA_UE',
            'CODIGO_MUNICIPIO',
            'NOME_MUNICIPIO',
            'NUMERO_ZONA',
            'CODIGO_CARGO',
            'NUMERO_CAND',
            'SQ_CANDIDATO',
            'NOME_CANDIDATO',
            'NOME_URNA_CANDIDATO',
            'DESCRICAO_CARGO',
            'COD_SIT_CAND_SUPERIOR',
            'DESC_SIT_CAND_SUPERIOR',
            'CODIGO_SIT_CANDIDATO',
            'DESC_SIT_CANDIDATO',
            'CODIGO_SIT_CAND_TOT',
            'DESC_SIT_CAND_TOT',
            'NUMERO_PARTIDO',
            'SIGLA_PARTIDO',
            'NOME_PARTIDO',
            'SEQUENCIAL_LEGENDA',
            'NOME_COLIGACAO',
            'COMPOSICAO_LEGENDA',
            'TOTAL_VOTOS',
        ]
    if ano in range(2014, 2017):
        return [
            'DATA_GERACAO',
            'HORA_GERACAO',
            'ANO_ELEICAO',
            'NUM_TURNO',
            'DESCRICAO_ELEICAO',
            'SIGLA_UF',
            'SIGLA_UE',
            'CODIGO_MUNICIPIO',
            'NOME_MUNICIPIO',
            'NUMERO_ZONA',
            'CODIGO_CARGO',
            'NUMERO_CAND',
            'SQ_CANDIDATO',
            'NOME_CANDIDATO',
            'NOME_URNA_CANDIDATO',
            'DESCRICAO_CARGO',
            'COD_SIT_CAND_SUPERIOR',
            'DESC_SIT_CAND_SUPERIOR',
            'CODIGO_SIT_CANDIDATO',
            'DESC_SIT_CANDIDATO',
            'CODIGO_SIT_CAND_TOT',
            'DESC_SIT_CAND_TOT',
            'NUMERO_PARTIDO',
            'SIGLA_PARTIDO',
            'NOME_PARTIDO',
            'SEQUENCIAL_LEGENDA',
            'NOME_COLIGACAO',
            'COMPOSICAO_LEGENDA',
            'TOTAL_VOTOS',
            'TRANSITO',
        ]


def tabela_detalhe_votacao_mun_zona(ano):
    if ano <= 2012:
        return [
            'DATA_GERACAO',
            'HORA_GERACAO',
            'ANO_ELEICAO',
            'NUM_TURNO',
            'DESCRICAO_ELEICAO',
            'SIGLA_UF',
            'SIGLA_UE',
            'CODIGO_MUNICIPIO',
            'NOME_MUNICIPIO',
            'NUMERO_ZONA',
            'CODIGO_CARGO',
            'DESCRICAO_CARGO',
            'QTD_APTOS',
            'QTD_SECOES',
            'QTD_SECOES_AGREGADAS',
            'QTD_APTOS_TOT',
            'QTD_SECOES_TOT',
            'QTD_COMPARECIMENTO',
            'QTD_ABSTENCOES',
            'QTD_VOTOS_NOMINAIS',
            'QTD_VOTOS_BRANCOS',
            'QTD_VOTOS_NULOS',
            'QTD_VOTOS_LEGENDA',
            'QTD_VOTOS_ANULADOS_APU_SEP',
            'DATA_ULT_TOTALIZACAO',
            'HORA_ULT_TOTALIZACAO',
        ]

    if ano <= 2014:
        return [
            'DATA_GERACAO',
            'HORA_GERACAO',
            'ANO_ELEICAO',
            'NUM_TURNO',
            'DESCRICAO_ELEICAO',
            'SIGLA_UF',
            'SIGLA_UE',
            'CODIGO_MUNICIPIO',
            'NOME_MUNICIPIO',
            'NUMERO_ZONA',
            'CODIGO_CARGO',
            'DESCRICAO_CARGO',
            'QTD_APTOS',
            'QTD_SECOES',
            'QTD_SECOES_AGREGADAS',
            'QTD_APTOS_TOT',
            'QTD_SECOES_TOT',
            'QTD_COMPARECIMENTO',
            'QTD_ABSTENCOES',
            'QTD_VOTOS_NOMINAIS',
            'QTD_VOTOS_BRANCOS',
            'QTD_VOTOS_NULOS',
            'QTD_VOTOS_LEGENDA',
            'QTD_VOTOS_ANULADOS_APU_SEP',
            'DATA_ULT_TOTALIZACAO',
            'HORA_ULT_TOTALIZACAO',
            'TRANSITO',
        ]

    if ano >= 2016:
        return [
            'DATA_GERACAO',
            'HORA_GERACAO',
            'ANO_ELEICAO',
            'NUM_TURNO',
            'DESCRICAO_ELEICAO',
            'SIGLA_UF',
            'SIGLA_UE',
            'CODIGO_MUNICIPIO',
            'NOME_MUNICIPIO',
            'NUMERO_ZONA',
            'CODIGO_CARGO',
            'DESCRICAO_CARGO',
            'QTD_APTOS',
            'QTD_SECOES',
            'QTD_SECOES_AGREGADAS',
            'QTD_APTOS_TOT',
            'QTD_SECOES_TOT',
            'QTD_COMPARECIMENTO',
            'QTD_ABSTENCOES',
            'QTD_VOTOS_NOMINAIS',
            'QTD_VOTOS_BRANCOS',
            'QTD_VOTOS_NULOS',
            'QTD_VOTOS_LEGENDA',
            'QTD_VOTOS_ANULADOS_APU_SEP',
            'DATA_ULT_TOTALIZACAO',
            'HORA_ULT_TOTALIZACAO',
            'TRANSITO',
            'QTD_VOTOS_ANULADOS',
        ]

def tabela_votacao_partido_mun_zona(ano):
    if ano <= 2012:
        return [
            'DATA_GERACAO',
            'HORA_GERACAO',
            'ANO_ELEICAO',
            'NUM_TURNO',
            'DESCRICAO_ELEICAO',
            'SIGLA_UF',
            'SIGLA_UE',
            'CODIGO_MUNICIPIO',
            'NOME_MUNICIPIO',
            'NUMERO_ZONA',
            'CODIGO_CARGO',
            'DESCRICAO_CARGO',
            'TIPO_LEGENDA',
            'NOME_COLIGACAO',
            'COMPOSICAO_LEGENDA',
            'SIGLA_PARTIDO',
            'NUMERO_PARTIDO',
            'NOME_PARTIDO',
            'QTDE_VOTOS_NOMINAIS',
            'QTDE_VOTOS_LEGENDA',
            'SEQUENCIAL_COLIGACAO',
        ]

    if ano in range(2014, 2017 + 1):
        return [
            'DATA_GERACAO',
            'HORA_GERACAO',
            'ANO_ELEICAO',
            'NUM_TURNO',
            'DESCRICAO_ELEICAO',
            'SIGLA_UF',
            'SIGLA_UE',
            'CODIGO_MUNICIPIO',
            'NOME_MUNICIPIO',
            'NUMERO_ZONA',
            'CODIGO_CARGO',
            'DESCRICAO_CARGO',
            'TIPO_LEGENDA',
            'NOME_COLIGACAO',
            'COMPOSICAO_LEGENDA',
            'SIGLA_PARTIDO',
            'NUMERO_PARTIDO',
            'NOME_PARTIDO',
            'QTDE_VOTOS_NOMINAIS',
            'QTDE_VOTOS_LEGENDA',
            'TRANSITO',
            'SEQUENCIAL_COLIGACAO',
        ]

def tabela_votacao_estados(ano=None):
    return [
        'NUM_TURNO',
        'SIGLA_UF',
        'NOME_CANDIDATO',
        'SIGLA_PARTIDO',
        'TOTAL_VOTOS',
    ]
