
VOTACAO_CANDIDATO_UF_ANO_ESTADO = [
    'DATA_GERACAO', 'HORA_GERACAO', 'ANO_ELEICAO',
    'NUM_TURNO', 'DESCRICAO_ELEICAO', 'SIGLA_UF',
    'SIGLA_UE', 'CODIGO_CARGO', 'NUMERO_CAND', 
    'SQ_CANDIDATO', 'NOME_CANDIDATO', 'NOME_URNA_CANDIDATO',
    'DESCRICAO_CARGO', 'COD_SIT_CAND_SUPERIOR', 'DESC_SIT_CAND_SUPERIOR',
    'CODIGO_SIT_CANDIDATO', 'DESC_SIT_CANDIDATO', 'CODIGO_SIT_CAND_TOT',
    'DESC_SIT_CAND_TOT', 'NUMERO_PARTIDO', 'SIGLA_PARTIDO',
    'NOME_PARTIDO', 'SEQUENCIAL_LEGENDA', 'NOME_COLIGACAO',
    'COMPOSICAO_LEGENDA', 'TOTAL_VOTOS'
]

